on:
  push:
    branches:
      - hotfixes/*
name: release-please-hotfixes
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: echo
        run: echo "Branch is ${{ steps.extract_branch.outputs.branch }}"
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          command: manifest
          versioning-strategy: "always-bump-patch"
          default-branch: ${{ steps.extract_branch.outputs.branch }}
