on:
  push:
    branches:
      - master
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          command: manifest
          versioning-strategy: "always-bump-minor"
      - uses: actions/checkout@v2
      - name: tag major and minor versions
        if: ${{ steps.release.outputs.release_created }}
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git remote add gh-token "https://${{ secrets.GITHUB_TOKEN }}@github.com/google-github-actions/release-please-action.git"
          sed -i 's/always-bump-minor/always-bump-patch/' release-please-config.json
          git add release-please-config.json
          git commit -m "Patch everything"
          git co -b hotfixes/v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.x
          git push origin hotfixes/v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.x || true
